part of 'resources.dart';

class ColorResources {
  final Color splashWord = Colors.black;
  final Color splashWordDark = Colors.white;
  final Color detailScreenContainer = Colors.white.withOpacity(0.4);
  final Color detailScreenContainerDark = Colors.black.withOpacity(0.4);
  final Color detailScreenIcons = Colors.black;
  final Color detailScreenIconsDark = Colors.white;
  final Color categoryContainerBorder = Colors.grey;
  final Color categoryContainer = Colors.grey.shade100;
  final Color categoryText = Colors.black;
  final Color categoryTextDark = Colors.white;
  final Color appBarTextIcon = Colors.black;
  final Color appBarTextIconDark = Colors.white;
  final Color appBar = Colors.white;
  final Color appBarDark = Colors.black;
  final Color textColorWhite = Colors.white;
  final Color textColorBlack = Colors.black;
  final Color textWhite24 = Colors.white24;
  final Color textFieldIcon = Colors.black;
  final Color background = Colors.white;
  final Color shimmerBase = Colors.grey.shade300;
  final Color shimmerBaseDark = Colors.grey.shade900;
  final Color shimmerHighlight = Colors.grey.shade100;
  final Color shimmerHighlightDark = Colors.grey.shade700;
  final Color selectedItemInNavigationBar = Colors.black;
  final Color selectedItemInNavigationBarDark = Colors.white;
  final Color selectedFavoriteItemInNavigationBar = Colors.red;
  final Color signInButton = Colors.amber;
  final Color boxShadow = Colors.black12;
  final Color circularProgress = Colors.white;
  final Color circularProgressDark = Colors.black;
  final Color signUpButton = const Color.fromARGB(106, 255, 255, 255);
  final Color welcomeBackgroundColor = Colors.transparent;
  final Color googleSignInUpText = Colors.white;
  final Color signUpInText = Colors.black;
  final Color newsDetailText = Colors.black;
  final Color newsDetailTextDark = Colors.white;
  final Color activeSwitch = Colors.black;
  final MaterialColor? primarySwatch = Colors.grey;
  final MaterialColor? primarySwatchDark = Colors.grey;
  final Color scaffoldBackgroundColor = Colors.white;
  final Color scaffoldBackgroundColorDark = Colors.grey.shade700;
  final Color focusedBorderTextField = Colors.black;
  final Color focusedBorderTextFieldDark = Colors.white;
}
